### ISSUE TITLE
Simdjson

### ISSUE THREAD

**Issue by ahorek** [ioquatix/ruby-json-benchmark#1]
hi, nice benchmarks! I would like to mention another library https://github.com/simdjson/simdjson which is faster than Oj.
It's just a parser (there's no dump part), so it's not a complete replacement, but still interesting.

**Comment by ioquatix** [comment]
Sure do you want to make a PR?

**Comment by ioquatix** [comment]
It would be neat to have a GH Action which ran the benchmarks. Just saying :p

**Comment by ahorek** [comment]
> It would be neat to have a GH Action which ran the benchmarks. Just saying :p

I agree https://github.com/ioquatix/ruby-json-benchmark/pull/3
